### ISSUE TITLE
Typo in /sgc.py(137)

### ISSUE THREAD

**Issue by liangmuxin** [neurodata/primitives-interfaces#32]
Hello, I am Muxin Liang from ISI and I am trying your primitives on graph datasets. And I guess I find a typo in your sgc/sgc.py for  v2018.6.5's release: G_lcc = LargestConnectedComponent(hyperpararms = hp_lcc).produce(inputs = self._training_inputs) should be G_lcc = LargestConnectedComponent(hyperparams = hp_lcc).produce(inputs = self._training_inputs)

**Comment by hhelm10** [comment]
Thanks for letting us know! The typo you mentioned is not present in the current iteration of the master branch. I will update the primitives and their metadata to match the most up to date versions after we fix a few more bugs. Sorry for any inconveniences!

HH
