### ISSUE TITLE
submit working primitives/pipelines to v2020.1.9

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/primitives-interfaces#64]
current working: load_graphs, lcc, ase, gclass, gclust

**Comment by bvarjavand** [comment]
flexed on em

**Comment by alyakin314** [comment]
@bvarjavand please don't turn this into a circus. 

current working pipelines:
            "vertexClassification": [
                "gclass_ase_pipeline",
                "gclass_lse_pipeline",
            "communityDetection": [
                "gmm_ase_pipeline",
                "gmm_lse_pipeline",
                 ],
            "linkPrediction": [
                "link_pred_pipeline",
                ].

try doing #72 and maybe #73 and then re-submit.

**Comment by alyakin314** [comment]
status quo of pipelines:
```
PIPELINES = {
            "graphMatching": [
                "sgm_pipeline",
            #     "sgm_pipeline_10"
                ],
            "vertexClassification": [
                "gclass_ase_pipeline",
                "gclass_lse_pipeline",
            #     "gclass_oosase_pipeline",
            #     "gclass_ooslse_pipeline",
            #     "sgc_pipeline"
                ],
            "communityDetection": [
                "gmm_ase_pipeline",
                "gmm_lse_pipeline",
            #     "gmm_oosase_pipeline",
            #     "gmm_ooslse_pipeline"
            #     "sgc_pipeline"
                ],
            "linkPrediction": [
                "link_pred_pipeline",
                ],
             }
```

merged into d3m.
