### ISSUE TITLE
fix broken primitives/pipelines

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/primitives-interfaces#65]
current broken: gclass, lse, sgm, link_pred_rc

**Comment by alyakin314** [comment]
currently broken primitives are:

all out of sample things:
- oosase
- ooslse
- oosgmm (ideally this would be merged into gmm ?)
all seeded graph matching things:
- sgc
- sgm
- sgvm
other:
- link_pred_se (I believe this is archaic and probably can be removed completly)

**Comment by alyakin314** [comment]
all primitives and pipelines other than the ones that use out of sample (see #75) work. 

closing this.
