### ISSUE TITLE
graph visualization (?) 

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/primitives-interfaces#69]
not sure about this myself @hhelm10

**Comment by alyakin314** [comment]
it would be nice if someone who is familiar enough (@bvarjavand ?) with graspy's plotting capabilities could give me an example notebook of what we do with graph visualization in general. 
i.e. it would be nice if it had one graph imported, ideally a dataset that d3m uses, and then a list of graph visualization tools that we have (pairplots, etc.)

**Comment by alyakin314** [comment]
resolved with me submitting net nomination and facebook notebooks to brian.
